version: '3'

services:
   db:
     image: mysql:5.7
     ports:
       - '3306:3306'
     volumes:
       - db_data_wp:/var/lib/mysql
       - ./mysql_dump:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress-local
       MYSQL_USER: wp-local
       MYSQL_PASSWORD: wp-local
    
   phpmyadmin:
    image: phpmyadmin
    restart: always    
    ports:
    - "8080:80"
    environment:
      UPLOAD_LIMIT: 1G

   wordpress:
     depends_on:
       - db

     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     working_dir: /var/www/html
     volumes:
       - ./wordpress/:/var/www/html/
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress-local
       WORDPRESS_DB_USER: wp-local
       WORDPRESS_DB_PASSWORD: wp-local
volumes:
    db_data_wp:
    